name: Publish 10x container (all)

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        description: '10x version to install'
        type: string
      docker_hub:
        required: true
        description: 'Which docker hub to publish to'
        type: choice
        options:
          - GHCR
      publish_pipeline:
        required: true
        type: boolean
        description: Publish Pipeline
        default: true
      publish_quarkus:
        required: true
        type: boolean
        description: Publish Quarkus
        default: true
      publish_lambda:
        required: true
        type: boolean
        description: Publish Lambda
        default: false

jobs:
  Pipeline:
    if: ${{ inputs.publish_pipeline }}
    name: Pipeline
    uses: ./.github/workflows/publish_10x_pipeline.yaml
    with:
      release_version: ${{ inputs.release_version }}
      docker_hub: ${{ inputs.docker_hub }}
    secrets: inherit

  Quarkus:
    if: ${{ inputs.publish_quarkus }}
    name: Quarkus
    uses: ./.github/workflows/publish_10x_quarkus.yaml
    with:
      release_version: ${{ inputs.release_version }}
      docker_hub: ${{ inputs.docker_hub }}
    secrets: inherit

  Lambda:
    if: ${{ inputs.publish_lambda }}
    name: Lambda
    uses: ./.github/workflows/publish_10x_lambda.yaml
    with:
      release_version: ${{ inputs.release_version }}
      docker_hub: ${{ inputs.docker_hub }}
      build_type: "Standard"
    secrets: inherit
