name: Publish Log10x Quarkus continer

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        description: 'Log10x version to install'
        type: string
      docker_hub:
        required: true
        description: 'Which docker hub to publish to'
        type: choice
        options:
          - GHCR

  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
      docker_hub:
        required: true
        type: string

jobs:
  prepare:
    name: Checks parameters and sets version
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.vars.outputs.image_name }}
      docker_file: ${{ steps.vars.outputs.docker_file }}
      docker_context: ${{ steps.vars.outputs.docker_context }}
      docker_repo: ${{ steps.vars.outputs.docker_repo }}
    steps:
      - name: Check parameters
        uses: actions/github-script@v7
        with:
          script: |
            if ("${{ inputs.docker_hub }}" != "GHCR") {
              core.setFailed("Only GHCR hub is supported")
            }

      - name: Prepare variables
        id: vars
        run: |
          echo "image_name=log10x-quarkus" >> "$GITHUB_OUTPUT"
          echo "docker_file=./main/quarkus/Dockerfile" >> "$GITHUB_OUTPUT"
          echo "docker_context=./main/quarkus" >> "$GITHUB_OUTPUT"

          if [ "${{ inputs.docker_hub }}" == "GHCR" ]; then
            echo "docker_repo=${{ vars.GHCR_REPO_NAME }}" >> "$GITHUB_OUTPUT"
          fi

  publish_x86:
    name: "Build x86 Quarkus ${{inputs.release_version}} to ${{inputs.docker_hub}}"
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Prepare release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
        run: |
          gh release download ${{ inputs.release_version }} --pattern "*quarkus*.tar" -R https://github.com/${{ vars.RELEASE_REPO }}
          ls -la
          tar -xvf log10x-quarkus*.tar -C ./main/quarkus/

      - name: Login to GHCR
        if: ${{ inputs.docker_hub == 'GHCR' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}
          tags: |
            type=raw,value=${{ inputs.release_version }}-amd64
            type=raw,value=latest-amd64,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish container
        uses: docker/build-push-action@v6
        with:
          file: ${{needs.prepare.outputs.docker_file}}
          context: ${{needs.prepare.outputs.docker_context}}
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.docker-meta.outputs.tags }}

  publish_aarch64:
    name: "Build aarch64 Quarkus ${{inputs.release_version}} to ${{inputs.docker_hub}}"
    runs-on: linux-arm64-2core
    needs: prepare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Prepare release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
        run: |
          gh release download ${{ inputs.release_version }} --pattern "*quarkus*.tar" -R https://github.com/${{ vars.RELEASE_REPO }}
          ls -la
          tar -xvf log10x-quarkus*.tar -C ./main/quarkus/

      - name: Login to GHCR
        if: ${{ inputs.docker_hub == 'GHCR' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}
          tags: |
            type=raw,value=${{ inputs.release_version }}-aarch64
            type=raw,value=latest-aarch64,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish container
        uses: docker/build-push-action@v6
        with:
          file: ${{needs.prepare.outputs.docker_file}}
          context: ${{needs.prepare.outputs.docker_context}}
          platforms: linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.docker-meta.outputs.tags }}

  publish_manifest:
    name: Publish proper manifest
    runs-on: ubuntu-latest
    needs:
      - prepare
      - publish_x86
      - publish_aarch64
    steps:
      - name: Login to GHCR
        if: ${{ inputs.docker_hub == 'GHCR' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest for ${{inputs.release_version}}
        run: |
          docker manifest create ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}} \
            --amend ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}-amd64 \
            --amend ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}-aarch64

          docker manifest annotate --arch amd64 --os linux ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}} ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}-amd64
          docker manifest annotate --arch arm64 --os linux ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}} ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}-aarch64
          docker manifest inspect ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}

          docker manifest push ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:${{inputs.release_version}}

      - name: Create manifest for latest
        run: |
          docker manifest create ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest \
            --amend ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest-amd64 \
            --amend ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest-aarch64

          docker manifest annotate --arch amd64 --os linux ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest-amd64
          docker manifest annotate --arch arm64 --os linux ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest-aarch64
          docker manifest inspect ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest

          docker manifest push ${{needs.prepare.outputs.docker_repo}}/${{needs.prepare.outputs.image_name}}:latest
